constexpr char* AboutText =
	"Glory Engine is copyright (C) 2020-2023 Robin Cordemans\n"
	"All rights reserved.\n"
	"\n"
	"License\n"
	"Given the early state of the engine, this software is for personal use only.\n"
	"\n"
	"Glory uses the following open source software\n"
	"\n"
	"MIT licensed libraries:\n"
	"- Dear Imgui - https://github.com/ocornut/imgui/\n"
	"- ImGuizmo - https://github.com/CedricGuillemet/ImGuizmo/\n"
	"- ImPlot - https://github.com/epezent/implot/\n"
	"- RapidJSON - https://github.com/Tencent/rapidjson/\n"
	"- stb image - https://github.com/nothings/stb/\n"
	"- yaml-cpp - https://github.com/jbeder/yaml-cpp\n"
	"- GLEW - https://glew.sourceforge.net/\n"
	"- GLM - https://github.com/g-truc/glm\n"
	"- Vulkan SDK - https://www.lunarg.com/vulkan-sdk/\n"
	"- Jolt Physics - https://github.com/jrouwe/JoltPhysics\n"
	"\n"
	"Other :\n"
	"- ASSIMP - http://assimp.org/\n"
	"- SDL - https://www.libsdl.org/index.php\n"
	"- SDL_image - https://github.com/libsdl-org/SDL_image\n"
	"- premake - https://premake.github.io/\n"
	"- shaderc - https://github.com/google/shaderc\n"
	"- SPIRV - cross - https://github.com/KhronosGroup/SPIRV-Cross\n"
	"- curl - https://curl.se/\n"
	"- esfw - https://github.com/SpartanJ/efsw\n"
	"- FontAwesome - https://fontawesome.com/\n"
	"- tinyfiledialogs - https://github.com/native-toolkit/libtinyfiledialogs\n";