constexpr char* AboutText =
	"Glory Engine is copyright (C) 2020-2025 Robin Cordemans\n"
	"All rights reserved.\n"
	"\n"
	"License\n"
	"Given the early state of the engine, this software is for personal use only.\n"
	"\n"
	"Glory uses the following open source software\n"
	"\n"
	"MIT licensed libraries:\n"
	"- Dear Imgui - https://github.com/ocornut/imgui/\n"
	"- ImGuizmo - https://github.com/CedricGuillemet/ImGuizmo/\n"
	"- ImPlot - https://github.com/epezent/implot/\n"
	"- RapidJSON - https://github.com/Tencent/rapidjson/\n"
	"- stb image - https://github.com/nothings/stb/\n"
	"- yaml-cpp - https://github.com/jbeder/yaml-cpp\n"
	"- GLEW - https://glew.sourceforge.net/\n"
	"- GLM - https://github.com/g-truc/glm\n"
	"- Vulkan SDK - https://www.lunarg.com/vulkan-sdk/\n"
	"- Jolt Physics - https://github.com/jrouwe/JoltPhysics\n"
	"- curl - https://curl.se/\n"
	"- FontAwesome - https://fontawesome.com/\n"
	"- Mono - https://www.mono-project.com/\n"
	"- HdriToCubemap - https://github.com/ivarout/HdriToCubemap\n"
	"\n"
	"Other:\n"
	"- ASSIMP - http://assimp.org/\n"
	"- SDL (zlib license) - https://www.libsdl.org/index.php\n"
	"- SDL_image (zlib license) - https://github.com/libsdl-org/SDL_image\n"
	"- SDL_mixer (zlib license) - https://github.com/libsdl-org/SDL_mixer\n"
	"- SteamAudio (Apache-2.0) - https://github.com/ValveSoftware/steam-audio\n"
	"- premake (BSD 3-Clause license) - https://premake.github.io/\n"
	"- shaderc (Apache-2.0) - https://github.com/google/shaderc\n"
	"- esfw - https://github.com/SpartanJ/efsw\n"
	"- tinyfiledialogs (zlib license) - https://github.com/native-toolkit/libtinyfiledialogs\n"
	"- FontAwesome font (SIL OFL 1.1) - https://fontawesome.com/\n"
	"- glslang (3-Clause BSD License) - https://github.com/KhronosGroup/glslang\n"
	"- SPIRV-cross (Apache-2.0) - https://github.com/KhronosGroup/SPIRV-Cross\n"
	"- SPIRV-tools (Apache-2.0) - https://github.com/KhronosGroup/SPIRV-Tools\n"
	"- zlib (zlib license) - https://www.zlib.net/\n"
	"- CRCpp (CRCpp license) - https://github.com/d-bahr/CRCpp/\n"
	"- FreeType (FreeType License) - https://github.com/freetype/freetype";