#pragma once
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define GLORY_EDITOR_VERSION_MAJOR 0
#define GLORY_EDITOR_VERSION_MINOR 1
#define GLORY_EDITOR_VERSION_SUBMINOR 0
#define GLORY_EDITOR_VERSION_RC 3
#ifndef GLORY_EDITOR_VERSION_RC
#defiine GLORY_EDITOR_VERSION_RC 0
#endif
#define GLORY_EDITOR_VERSION_NIGHTLY


#if GLORY_EDITOR_VERSION_RC > 0
#define GLORY_EDITOR_VERSION TOSTRING(GLORY_EDITOR_VERSION_MAJOR.GLORY_EDITOR_VERSION_MINOR.GLORY_EDITOR_VERSION_SUBMINOR.rc-GLORY_EDITOR_VERSION_RC)
#else
#define GLORY_EDITOR_VERSION TOSTRING(GLORY_EDITOR_VERSION_MAJOR.GLORY_EDITOR_VERSION_MINOR.GLORY_EDITOR_VERSION_SUBMINOR)
#endif

namespace Glory::Editor
{
	constexpr char* GloryEditorVersion = GLORY_EDITOR_VERSION;
}
