#pragma once
#include "TransformSystem.h"
#include "MeshRenderSystem.h"
#include "MeshFilterSystem.h"
#include "CameraSystem.h"
#include "LookAtSystem.h"
#include "SpinSystem.h"
#include "LightSystem.h"
#include "ScriptedSystem.h"