name: Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "release-0.1.0" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./GloryEngine
  # Path to premake5.exe
  PREMAKE_PATH: "third-party/premake/premake5.exe"
  # Premake arg
  PREMAKE_ARG: vs2022

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  BUILD_PATH: ./GloryEngine/Build/Release/x64/Launcher
  UTIL_TEST_PATH: ./bin/Engine/Release/x64/Tests
  EDITOR_TEST_PATH: ./bin/Engine/Release/x64/Tests/Editor

permissions:
  contents: read

jobs:
  build-editor-win64:
    runs-on: [self-hosted, windows]
    # runs-on: windows-2022
    environment: 'dev'

    steps:
    - name: Load .env
      shell: bash
      run: |
        if [ -f ../../../.env ]; then
          while IFS= read -r line || [ -n "$line" ]; do
            [[ "$line" =~ ^#.*$ ]] || [ -z "$line" ] && continue
            echo "$line" >> $GITHUB_ENV
          done < ../../../.env
        else
          echo "Relative .env file not found"
        fi

    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Install mono
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      shell: bash
      run: ./install-mono.sh

    - name: Check vulkan install
      shell: bash
      run: |
          if [ -d "/C/VulkanSDK/1.4.321.1" ]; then
            echo "Vulkan SDK found, skipping installation..."
            echo "SKIP_VULKAN=true" >> $GITHUB_ENV
          else
            echo "Vulkan SDK not found, vulkan will be installed..."
            echo "SKIP_VULKAN=false" >> $GITHUB_ENV
          fi

    - name: Install Vulkan SDK
      if: env.SKIP_VULKAN != 'true'
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        vulkan_version: 1.4.321.1
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        stripdown: true
        install_swiftshader: false
        install_lavapipe: false

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore cached dependencies
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      env:
        cache-name: cache-dependencies
      with:
        path: ${{env.SOLUTION_FILE_PATH}}/Dependencies
        key: ${{ runner.os }}-dependencies

    - if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
      name: Install dependencies
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      shell: bash
      run: ./install-dependencies.sh Release

    - if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
      name: Cache dependencies
      id: cache-dependencies-save
      uses: actions/cache/save@v3
      env:
        cache-name: cache-dependencies
      with:
        path: ${{env.SOLUTION_FILE_PATH}}/Dependencies
        key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

    - name: Run premake5
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: ${{env.PREMAKE_PATH}} ${{env.PREMAKE_ARG}}

    - name: Build
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 .

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Util Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      env:
        PYTHONUNBUFFERED: "1"
      run: python RunTests.py --path=${{env.UTIL_TEST_PATH}}

    - if: env.GRAPHICS_AVAILABLE == 'true'
      name: Editor Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      env:
        PYTHONUNBUFFERED: "1"
      run: python RunTests.py --path=${{env.EDITOR_TEST_PATH}}

    - name: Upload editor Artifact
      uses: actions/upload-artifact@v4
      with:
        name: editor-zip
        path: ${{env.BUILD_PATH}}
        retention-days: 30
